<?php
/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\ProductBundle\Entity;

use Sonata\ProductBundle\Entity\BaseProduct as BaseProduct;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
abstract class Product extends BaseProduct
{
    /**
     * @var integer $id
     */
    protected $id;

    /**
     * @var \CTI\CibourBundle\Entity\Produttore
     */
    private $produttore;

    private $macroregione;

    private $voto;

    private $pezzatura;

    private $tipo_dieta;

    private $superfood;

    /**
     * @var boolean $gluten_free
     */
    private $gluten_free;

    private $metodo_produzione;
    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param int $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * Set produttore
     *
     * @param \CTI\CibourBundle\Entity\Produttore $produttore
     * @return Prodotto
     */
    public function setProduttore(\CTI\CibourBundle\Entity\Produttore $produttore = null)
    {
        $this->produttore = $produttore;

        return $this;
    }

    /**
     * Get produttore
     *
     * @return \CTI\CibourBundle\Entity\Produttore
     */
    public function getProduttore()
    {
        return $this->produttore;
    }
}
