imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache:                         apc
#
#doctrine:
#    orm:
#        entity_managers:
#            default:
#                metadata_cache_driver: apc
#                query_cache_driver:    apc
#                result_cache_driver:   apc

monolog:
    handlers:
        api:
            type: stream
            path: %kernel.root_dir%/../public_html/api.log
            level: info
            channels: api
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
            channels:     '!api'
        nested:
            type:         stream
            path:         %kernel.logs_dir%/%kernel.name%_%kernel.environment%.log
            level:        debug