sonata_delivery:
    methods:
        free: ~
        one_day:   application.sonata.delivery.one_day

    services:
        free_address_required:
            name: Free
            priority: 1
            code: free

    selector: sonata.delivery.selector.default

# Enable Doctrine to map the provided entities
doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    ApplicationSonataDeliveryBundle: ~
                    SonataDeliveryBundle: ~
