sonata_product:
    products:
        cibour.product.prodotto:
            provider: cibour.product.prodotto.type
            manager: cibour.product.prodotto.manager

    seo:
        product:
            site: '@cibour'
            creator: '@Riccardo Cartei'
            domain: 'http://cibour.com'
            media_prefix: 'http://cibour.com'
            media_format: 'reference'



# Enable Doctrine to map the provided entities
doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    ApplicationSonataProductBundle: ~
                    SonataProductBundle: ~