sonata_payment:
    methods:
        pass: ~
        paypal: ~
        xpay: cibour.payment.method.xpay

    services:
        paypal:
            name:                 Paypal
            code:                 paypal

            transformers:
                basket: sonata.payment.transformer.basket
                order:  sonata.payment.transformer.order

            options:
                web_connector_name: curl

                account:            amministrazione@latavolaitaliana.org
                cert_id:            SAAZA6Z6D94H4
                url_action:         https://www.sandbox.paypal.com/cgi-bin/webscr

                debug: true
                class_order:        Application\Sonata\OrderBundle\Entity\Order
                url_callback:       sonata_payment_callback
                url_return_ko:      sonata_payment_error
                url_return_ok:      sonata_payment_confirmation

                method:             encryptViaBuffer

                key_file:           %kernel.root_dir%/my-prvkey.pem
                cert_file:          %kernel.root_dir%/my-pubcert.pem
                paypal_cert_file:   %kernel.root_dir%/sandbox.paypal_cert_pem.txt

                openssl:            C:\xampp\apache\bin\openssl.exe

        pass:
            name:    Bonifico Bancario
            code:    pass
            browser: sonata.payment.browser.curl

            transformers:
                basket: sonata.payment.transformer.basket
                order:  sonata.payment.transformer.order

            options:
                shop_secret_key: assdsds
                url_callback:    sonata_payment_callback
                url_return_ko:   sonata_payment_error
                url_return_ok:   sonata_payment_confirmation


    # service which find the correct payment methods for a basket
    selector: sonata.payment.selector.simple

    # service which generate the correct order and invoice number
    generator: sonata.payment.generator.mysql

    transformers:
        order:  sonata.payment.transformer.order
        basket: sonata.payment.transformer.basket

# Enable Doctrine to map the provided entities
doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    ApplicationSonataPaymentBundle: ~
                    SonataPaymentBundle: ~