<?php
/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\BasketBundle\Entity;

use Sonata\BasketBundle\Entity\BaseBasketElement as BaseBasketElement;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class BasketElement extends BaseBasketElement
{

    /**
     * @var integer $id
     */
    protected $id;

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * {@inheritdoc}
     */
    public function getUnitPrice($vat = false)
    {
        $price = $this->unitPrice;

        if (!$vat && true === $this->isPriceIncludingVat()) {
            $price = bcdiv($price, bcadd(1, bcdiv($this->getVatRate(), 100)));
        }

        if ($vat && false === $this->isPriceIncludingVat()) {
            $price = bcmul($price, bcadd(1, bcdiv($this->getVatRate(), 100)));
        }

        return $price;
    }
}