<?php
/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\InvoiceBundle\Entity;

use Sonata\InvoiceBundle\Entity\BaseInvoice as BaseInvoice;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class Invoice extends BaseInvoice
{

    /**
     * @var integer $id
     */
    protected $id;

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }
    /**
     * @var string
     */
    protected $partita_iva;

    /**
     * @var string
     */
    protected $codice_fiscale;

    /**
     * @var string
     */
    protected $provincia;

    /**
     * @var boolean
     */
    protected $richiesta_fattura = false;

    /**
     * @var string
     */
    protected $note;

    /**
     * Set partita_iva
     *
     * @param string $partitaIva
     * @return Invoice
     */
    public function setPartitaIva($partitaIva)
    {
        $this->partita_iva = $partitaIva;

        return $this;
    }

    /**
     * Get partita_iva
     *
     * @return string 
     */
    public function getPartitaIva()
    {
        return $this->partita_iva;
    }

    /**
     * Set codice_fiscale
     *
     * @param string $codiceFiscale
     * @return Invoice
     */
    public function setCodiceFiscale($codiceFiscale)
    {
        $this->codice_fiscale = $codiceFiscale;

        return $this;
    }

    /**
     * Get codice_fiscale
     *
     * @return string 
     */
    public function getCodiceFiscale()
    {
        return $this->codice_fiscale;
    }

    /**
     * Set provincia
     *
     * @param string $provincia
     * @return Invoice
     */
    public function setProvincia($provincia)
    {
        $this->provincia = $provincia;

        return $this;
    }

    /**
     * Get provincia
     *
     * @return string 
     */
    public function getProvincia()
    {
        return $this->provincia;
    }

    /**
     * Set richiesta_fattura
     *
     * @param boolean $richiestaFattura
     * @return Invoice
     */
    public function setRichiestaFattura($richiestaFattura)
    {
        $this->richiesta_fattura = $richiestaFattura;

        return $this;
    }

    /**
     * Get richiesta_fattura
     *
     * @return boolean 
     */
    public function getRichiestaFattura()
    {
        return $this->richiesta_fattura;
    }

    /**
     * Set note
     *
     * @param string $note
     * @return Invoice
     */
    public function setNote($note)
    {
        $this->note = $note;

        return $this;
    }

    /**
     * Get note
     *
     * @return string 
     */
    public function getNote()
    {
        return $this->note;
    }
}
